### PR TITLE
Database with relations to master

### PR DESCRIPTION
**Pull request by ebenitz18**

### CODE REVIEW

**Comment by DaniN12** [comment]
No conflicts!!!!!!!

**Comment by Keli112** [comment]
I need a coffee XD

**Comment by ebenitz18** [comment]
NO conflicts, let's go 🥇

**Comment by Keli112** [comment]
👍 fat finger up

**Comment by Ruthianita** [comment]
we are the frikin  best team letssss gooooooooooooo 🚀🥇

**Pull request merged**
